version: '3'

services:
  cadvisor:
    image: google/cadvisor
    ports:
      - 8080:8080
  #  volumes:
  #    - /:/rootfs:ro
  #    - /var/run:/var/run:rw
  #    - /sys:/sys:ro
  #    - /var/lib/docker:/var/lib/docker:ro

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - pushgateway:pushgateway
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/plugins:/etc/grafana/plugins

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox
    restart: unless-stopped
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
  #  dns: 8.8.8.8
