global:
  scrape_interval:     60s
  evaluation_interval: 60s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-stack-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'machine-vm'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'projekty-pracuj-pl-status'
    scrape_interval: 60s
    scrape_timeout: 5s
    static_configs:
      - targets: ['projekty.pracuj.pl:80']
    metrics_path: /status.php

  - job_name: 'jarvis-devire-eu-status'
    scrape_interval: 60s
    scrape_timeout: 5s
    static_configs:
      - targets: ['jarvis.devire.eu:80']
    metrics_path: /status.php

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://projekty.pracuj.pl/login
        - https://jarvis.devire.eu/admin/login
        - https://funduszesaturntfi.pl/login
        - https://system.soluton.no/login
        - https://epicode.pl/
        - https://ddwloclawek.pl/pl/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
